version: '2'

services:
  elasticsearch_master:
    build:
      context: elasticsearch/
    command: elasticsearch -Dnode.name=M1 -Dnode.master=1 -Dnode.data=0
    ports:
      - "9210:9200"
    volumes:
      - ./elasticsearch/conf:/etc/elasticsearch
    networks:
      - docker_net
    tty: false
    stdin_open: false
  elasticsearch_data_1:
    build:
      context: elasticsearch/
    command: elasticsearch -Dnode.name=D1 -Dnode.master=0 -Dnode.data=1 -Ddiscovery.zen.ping.unicast.hosts=elasticsearch_master
    ports:
      - "9201:9200"
    links:
      - elasticsearch_master
    volumes:
      - "/opt/elasticsearch/data"
      - ./elasticsearch/conf:/etc/elasticsearch
    networks:
      - docker_net
    tty: false
    stdin_open: false
#  kibana:
#    build:
#      context: kibana/
#    ports:
#      - "5601:5601"
#    links:
#      - "elasticsearch_master:elasticsearch"
#    depends_on:
#      - elasticsearch_master
#    networks:
        #      - docker_net
  nginx:
    image: nginx
    ports:
      - "9200:9200"
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx
    networks:
      - docker_net
    links:
      - "elasticsearch_data_1:esd1"
      - "elasticsearch_master:esm"
  logstash:
    image: logstash:5.1.1
#    command: "-f /etc/logstash/conf.d/ --debug"
    command: "-f /etc/logstash/conf.d/"
    volumes:
      - ./logstash/conf:/etc/logstash/conf.d
    ports:
      - "1984:1984"
    links:
      - "nginx:esnginx1"
    networks:
      - docker_net
    depends_on:
      - nginx


networks:
  docker_net:
    driver: bridge
