version: '2'

services:
  elasticsearch_master:
    build:
      context: elasticsearch/
      args:
        nodename: M1
        master: 1
        data: 0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_net
    tty: false
    stdin_open: false
  elasticsearch_data_1:
    build:
      context: elasticsearch/
      args:
        nodename: D1
        master: 0
        data: 1
    ports:
      - "9201:9200"
    links:
      - elasticsearch_master
    volumes:
      - "/opt/elasticsearch/data"
    networks:
      - docker_net
    tty: false
    stdin_open: false
  elasticsearch_data_2:
    build:
      context: elasticsearch/
      args:
        nodename: D2
        master: 0
        data: 1
    ports:
      - "9202:9200"
    links:
      - elasticsearch_master
    volumes:
      - "/opt/elasticsearch/data"
    networks:
      - docker_net
    tty: false
    stdin_open: false
  logstash:
    image: logstash:2.3.4
#    command: "-f /etc/logstash/conf.d/ --debug"
    command: "-f /etc/logstash/conf.d/"
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "1984:1984"
    links:
      - "elasticsearch_data_1:es1"
      - "elasticsearch_data_2:es2"
    networks:
      - docker_net
    depends_on:
      - elasticsearch_data_1
  kibana:
    image: kibana:4.6.1
    ports:
      - "5601:5601"
    links:
      - "elasticsearch_master:elasticsearch"
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
