version: '2'

services:
  logstash:
    build:
      context: logstash/
    command: "-f /etc/logstash/conf.d/"
    volumes:
      - ./logstash/conf:/etc/logstash/conf.d
    ports:
      - "9092:9092"
    networks:
      - docker_net
  metricbeat:
    build:
      context: metricbeat/
    command: metricbeat -e -v -c /metricbeat/metricbeat.yml 
    networks:
      - docker_net
    volumes:
      - ./metricbeat/metricbeat.yml:/metricbeat/metricbeat.yml
    depends_on:
      - logstash


networks:
  docker_net:
    driver: bridge
