metricbeat.modules.reload:

  # Glob pattern for configuration reloading
  path: ${path.config}/conf.d/*.yml

  # Period on which files under path should be checked for chagnes
  period: 10s

  # Set to true to enable config reloading
  enabled: false

#==========================  Modules configuration ============================
metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets:
    - cpu
    #- load
    #- core
    #- diskio
    #- filesystem
    #- fsstat
    - memory
    #- network
    #- process
    #- socket
  enabled: true
  period: 10s
  processes: ['.*']

#================================ General ======================================


# If this option is set to true, the custom fields are stored as top-level
# fields in the output document instead of being grouped under a fields
# sub-dictionary. Default is false.
#fields_under_root: true

#================================ Outputs ======================================

#----------------------------- Logstash output ---------------------------------
output.logstash:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # The Logstash hosts
  hosts: ["logstash:5044"]

#================================ Logging ======================================

# Logging to rotating files files. Set logging.to_files to false to disable logging to
# files.
logging.to_files: true
logging.files:
